### PR TITLE
Use `error` helper to set exit codes correctly

### PR DESCRIPTION
**Pull request by elpete**

### CODE REVIEW

**Comment by jcberquist** [comment]
I considered this approach, but I decided against it, since it exits the functions early - if the `timeit` flag is set, I would still like that output. I don't currently set the exit code when processing a single file, so that should be added (and the one in the settings print seems reasonable), but I am already setting the exit code in the`formatFiles()` function, right?

**Comment by elpete** [comment]
That was my thought, but the exit code was still coming back as `0` even when I set it directly in the failure blocks with `setExitCode( 1 )`.

**Comment by jcberquist** [comment]
That is odd, in testing on OSX I tried `box "cfformat *.cfc --check"; echo $?` (with a failing file) and the echoed exit code is `1` for me.

**Comment by elpete** [comment]
Strange.  I definitely tested it before submitting this PR, but now it is working for me as well.  Sorry about that!

**Pull request closed without merging**
